name: testing

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: '☁️ checkout repository'
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: '📦 Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: '📦 Install Dependencies'
        run: npm ci

      - name: '✅ Run Vitest'
        run: npx vitest --coverage.enabled true

      - name: '📓 Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your Vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: './'
          json-summary-path: 'logs/coverage/coverage-summary.json'
          json-final-path: 'logs/coverage/coverage-final.json'
